1)ASSIGNMENT

//1. CREATE CLIENT_MASTER TABLE

CREATE TABLE CLIENT_MASTER(CLIENTNO VARCHAR(6),NAME VARCHAR(20),CITY VARCHAR(15),PINCODE NUMBER(8),STATE VARCHAR(15),BALDUE NUMBER(10,2),PRIMARY KEY(CLIENTNO));


INSERT ALL
INTO CLIENT_MASTER(CLIENTNO,NAME,CITY,PINCODE,STATE,BALDUE) VALUES('C00001' , 'INDRESH' , 'BILASPUR' , 495330 ,'CG' ,15000)
INTO CLIENT_MASTER(CLIENTNO,NAME,CITY,PINCODE,STATE,BALDUE) VALUES('C00002' , 'AKSHAY' , 'KORBA' , 495001 ,'CG' ,0)
INTO CLIENT_MASTER(CLIENTNO,NAME,CITY,PINCODE,STATE,BALDUE) VALUES('C00003' , 'SHASHANK' , 'RAIPUR' , 495006 ,'CG' ,5000)
INTO CLIENT_MASTER(CLIENTNO,NAME,CITY,PINCODE,STATE,BALDUE) VALUES('C00004' , 'KHILESH' , 'DHAMTARI' , 495009 ,'CG' ,0)
INTO CLIENT_MASTER(CLIENTNO,NAME,CITY,PINCODE,STATE,BALDUE) VALUES('C00005' , 'KHEMDAS' , 'MUNGELI' , 495010 ,'CG' ,2000)
INTO CLIENT_MASTER(CLIENTNO,NAME,CITY,PINCODE,STATE,BALDUE) VALUES('C00006' , 'JAY' , 'BILASPUR' , 495333 ,'CG' ,0)

SELECT * FROM dual;



//2. CREATE PRODUCT_MASTER TABLE

CREATE TABLE PRODUCT_MASTER(PRODUCTNO VARCHAR(6),DESCRIPTION VARCHAR(15),PROFITPERCENT NUMBER(4,2),QTYONHAND NUMBER(8),REORDERLVL NUMBER(8),SELLPRICE NUMBER(8,2),COSTPRICE NUMBER(8,2),PRIMARY KEY(PRODUCTNO));

INSERT ALL
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00001' , 'T-SHIRT' , 5 , 200 ,50 ,350,250)
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00002' , 'SHIRT' , 6 , 150 ,50 ,500,350)
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00003' , 'COTTON_JEANS' , 5 , 100 ,20 ,600,450)
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00004' , 'JEANS' , 5 , 100 ,20 ,750,500)
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00005' , 'TROUSERS' , 2 , 150 ,50 ,850,550)
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00006' , 'PULL_OVERS' , 2.5 , 80 ,30 ,700,450)
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00007' , 'DENIM_SHIRTS' , 4 , 100 ,40 ,350,250)
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00008' , 'LYCRA_TOPS' , 5 , 70 ,30 ,300,175)
INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION,PROFITPERCENT,QTYONHAND,REORDERLVL,SELLPRICE,COSTPRICE) VALUES('P00009' , 'SKIRTS' , 5 , 75 ,30 ,450,300)
SELECT * FROM dual;



//3. CREATE SALESMAN_MASTER TABLE

CREATE TABLE SALESMAN_MASTER(SALESMANNO VARCHAR(6),NAME VARCHAR(20),ADRESS VARCHAR(30),CITY VARCHAR(8),PINCODE NUMBER(8),STATE VARCHAR(20),SALAMT NUMBER(8,2),TGTTOGET NUMBER(6,2),YTDSALES NUMBER(6,2),REMARK VARCHAR(60),PRIMARY KEY(SALESMANNO));

INSERT ALL
INTO SALESMAN_MASTER(SALESMANNO,NAME,ADRESS,CITY ,PINCODE,STATE ,SALAMT,TGTTOGET,YTDSALES,REMARK)VALUES('S00001' , 'AMAN' , 'KONI','BILASPUR', 495001 ,'CG' ,3000,100,50,'GOOD');
INTO SALESMAN_MASTER(SALESMANNO,NAME,ADRESS,CITY ,PINCODE,STATE ,SALAMT,TGTTOGET,YTDSALES,REMARK) VALUES('S00002' , 'OMKAR' , 'TAKHATPUR','BILASPUR', 495330 ,'CG' ,3000,200,100,'GOOD')
INTO SALESMAN_MASTER(SALESMANNO,NAME,ADRESS,CITY ,PINCODE,STATE ,SALAMT,TGTTOGET,YTDSALES,REMARK) VALUES('S00003' , 'RAJ' , 'BIRGAON','RAIPUR', 495009 ,'CG' ,3000,200,100,'GOOD')
INTO SALESMAN_MASTER(SALESMANNO,NAME,ADRESS,CITY ,PINCODE,STATE ,SALAMT,TGTTOGET,YTDSALES,REMARK) VALUES('S00004' , 'ASHISH' , 'BHILAI','DURG', 495110 ,'CG' ,3500,200,150,'GOOD')
SELECT * FROM dual;




//ASSIGNMENT ANSWERS===

1) SELECT NAME FROM CLIENT_MASTER;

2) SELECT * FROM CLIENT_MASTER;

3) SELECT NAME,CITY,STATE FROM CLIENT_MASTER;

4) SELECT DESCRIPTION FROM PRODUCT_MASTER;

5) SELECT NAME FROM CLIENT_MASTER WHERE CITY='BILASPUR';

6) SELECT NAME FROM SALESMAN_MASTER WHERE SALAMT=3000;

7) UPDATE CLIENT_MASTER SET CITY='BILASPUR' WHERE CLIENTNO='C00005';

8) UPDATE CLIENT_MASTER SET BALDUE=10000 WHERE CLIENTNO='C00001';

9) UPDATE PRODUCT_MASTER SET COSTPRICE=950 WHERE DESCRIPTION='T-SHIRT';

10) UPDATE SALESMAN_MASTER SET CITY='RAIPUR' ;

11) DELETE FROM SALESMAN_MASTER WHERE SALAMT=3500;

12) DELETE FROM PRODUCT_MASTER WHERE QTYONHAND=100;

13) DELETE FROM CLIENT_MASTER WHERE CITY ='BILASPUR';

14) ALTER TABLE CLIENT_MASTER ADD(TELEPHONE NUMBER(10));

15) ALTER TABLE PRODUCT_MASTER MODIFY(SELLPRICE NUMBER(10,2));

16) DROP TABLE CLIENT_MASTER;

17) ALTER TABLE SALESMAN_MASTER RENAME TO SMAN_MASTER;


=========================================================================================================================================================================================================================================

 
 
 
