(3)ASSIGNMENT

NOTE :-

(1)DROP ALL THE FOLLOWING TABLES AND RECREATE TABLES --
 
	(A)CLIENT_MASTER (B)PRODUCT_MASTER (C)SALESMAN_MASTER       	(D)SALES_ORDER (E) SALES_ORDER_DETAILS.


(2)IN SOME QUESTIONS VALUES ARE CHANGED ACCORDING TO TABLES BECAUSE RECORDS ARE NOT FOUND



//1.EXERCISE ON USING HAVING AND GROUP BY CLAUSES-


1)SELECT DESCRIPTION, SUM(QTYDISP) FROM PRODUCT_MASTER PM, SALES_ORDER_DETAILS SOD WHERE PM.PRODUCTNO = SOD.PRODUCTNO GROUP BY DESCRIPTION;


2)SELECT SOD.PRODUCTNO, PM.DESCRIPTION, SUM(SOD.QTYDISP * SOD.PRODUCTRATE) SALESPERPRODUCT FROM SALES_ORDER_DETAILS SOD, PRODUCT_MASTER PM WHERE PM.PRODUCTNO = SOD.PRODUCTNO GROUP BY SOD.PRODUCTNO, PM.DESCRIPTION;


3)SELECT CM.CLIENTNO, AVG(SOD.QTYDISP) AVGSALES FROM CLIENT_MASTER CM ,SALES_ORDER_DETAILS SOD WHERE SOD.ORDERNO = SOD.ORDERNO GROUP BY CM.CLIENTNO HAVING MAX(SOD.QTYORDERED * SOD.PRODUCTRATE) > 2000;


4)SELECT SO.ORDERNO, SO.ORDERDATE, SUM(SOD.QTYORDERED * SOD.PRODUCTRATE) ORDERBILLED FROM SALES_ORDER SO, SALES_ORDER_DETAILS SOD WHERE SOD.ORDERNO = SO.ORDERNO AND BILLYN = 'Y' AND TO_CHAR(ORDERDATE,'MON') = 'JUN' GROUP BY SO.ORDERNO, SO.ORDERDATE;



//2.EXERCISE ON JOIN AND CORRELATION CLAUSES-BUT HERE CORRELATION IS USED


1)SELECT SOD.PRODUCTNO, PM.DESCRIPTION FROM SALES_ORDER_DETAILS SOD, PRODUCT_MASTER PM, SALES_ORDER SO, CLIENT_MASTER CM WHERE PM.PRODUCTNO = SOD.PRODUCTNO AND SO.ORDERNO = SOD.ORDERNO AND CM.CLIENTNO = SO.CLIENTNO AND CM.NAME = 'INDRESH';

2)SELECT SOD.PRODUCTNO, PM.DESCRIPTION, SUM(SOD.QTYORDERED) FROM SALES_ORDER_DETAILS SOD, SALES_ORDER SO, PRODUCT_MASTER PM WHERE PM.PRODUCTNO = SOD.PRODUCTNO AND SO.ORDERNO = SOD.ORDERNO AND TO_CHAR(DELYDATE, 'MON') = 'JUL' GROUP BY SOD.PRODUCTNO, PM.DESCRIPTION;

3)SELECT DISTINCT PM.PRODUCTNO, DESCRIPTION FROM SALES_ORDER_DETAILS SOD, PRODUCT_MASTER PM WHERE PM.PRODUCTNO = SOD.PRODUCTNO;

4)SELECT CM.CLIENTNO, CM.NAME FROM SALES_ORDER_DETAILS SOD, SALES_ORDER SO, PRODUCT_MASTER PM, CLIENT_MASTER CM WHERE PM.PRODUCTNO = SOD.PRODUCTNO AND SO.ORDERNO = SOD.ORDERNO AND CM.CLIENTNO = SO.CLIENTNO AND DESCRIPTION = 'T-SHIRT';

5)SELECT SOD.PRODUCTNO, SOD.ORDERNO FROM SALES_ORDER_DETAILS SOD, SALES_ORDER SO, PRODUCT_MASTER PM WHERE SO.ORDERNO = SOD.ORDERNO AND PM.PRODUCTNO = SOD.PRODUCTNO AND SOD.QTYORDERED < 101 AND DESCRIPTION ='SHIRT';

6)SELECT SOD.PRODUCTNO, PM.DESCRIPTION, SUM(QTYORDERED) UNITS_ORDERED FROM SALES_ORDER_DETAILS SOD, SALES_ORDER SO, PRODUCT_MASTER PM, CLIENT_MASTER CM WHERE SO.ORDERNO = SOD.ORDERNO AND PM.PRODUCTNO = SOD.PRODUCTNO AND CM.CLIENTNO = SO.CLIENTNO AND (CM.NAME = 'INDRESH' OR CM.NAME = 'KHILESH') GROUP BY SOD.PRODUCTNO, PM.DESCRIPTION;

7)SELECT SO.CLIENTNO, SOD.PRODUCTNO, PM.DESCRIPTION, SUM(QTYORDERED) UNITS_ORDERED FROM SALES_ORDER SO, SALES_ORDER_DETAILS SOD, PRODUCT_MASTER PM, CLIENT_MASTER CM WHERE SO.ORDERNO = SOD.ORDERNO AND SOD.PRODUCTNO = PM.PRODUCTNO AND SO.CLIENTNO = CM.CLIENTNO GROUP BY SO.CLIENTNO, SOD.PRODUCTNO, PM.DESCRIPTION HAVING SO.CLIENTNO = 'C00001' OR SO.CLIENTNO = 'C00002';




//3.EXERCISE ON SUBQUERIES --

1)SELECT PRODUCTNO, DESCRIPTION FROM PRODUCT_MASTER WHERE PRODUCTNO NOT IN(SELECT PRODUCTNO FROM SALES_ORDER_DETAILS);

2)SELECT NAME, STATE, CITY, STATE, PINCODE FROM CLIENT_MASTER WHERE CLIENTNO IN(SELECT CLIENTNO FROM SALES_ORDER WHERE ORDERNO = 'O19001');

3)SELECT CLIENTNO, NAME FROM CLIENT_MASTER WHERE CLIENTNO IN(SELECT CLIENTNO FROM SALES_ORDER WHERE TO_CHAR(ORDERDATE, 'MON,YY') > 'JUL,04');

4)SELECT CLIENTNO, NAME FROM CLIENT_MASTER WHERE CLIENTNO IN(SELECT CLIENTNO FROM SALES_ORDER WHERE ORDERNO IN(SELECT ORDERNO FROM SALES_ORDER_DETAILS WHERE PRODUCTNO IN(SELECT PRODUCTNO FROM PRODUCT_MASTER WHERE DESCRIPTION = 'T-SHIRT')));

5)SELECT NAME FROM CLIENT_MASTER WHERE CLIENTNO IN(SELECT CLIENTNO FROM SALES_ORDER WHERE ORDERNO IN(SELECT ORDERNO FROM SALES_ORDER_DETAILS WHERE(QTYORDERED * PRODUCTRATE) >= 2000));
